[package]
authors = ["Effnote <effnote@gmail.com>"]
name = "rsfchat"
version = "0.0.1"

[dependencies]
cursive = "0.6.4"
futures = "0.1.15"
serde = "1.0.11"
tokio-core = "0.1.9"

[dependencies.fchat]
git = "https://github.com/effnote/libfchat"
