[package]
authors = ["Effnote <effnote@gmail.com>"]
name = "rsfchat"
version = "0.0.2"
edition = "2018"

[dependencies]
chrono = "0.4.10"
cursive = "0.20.0"
serde = "1.0.103"
futures = "0.3.1"
derive_more = "0.99.18"

[dependencies.tokio]
version = "0.2.2"
features = ["time", "sync", "stream"]

[dependencies.fchat]
git = "https://github.com/effnote/libfchat"
branch = "tokio2"
